import type { GeoPosSuggestion } from "@/const/geo-pos-list";
import { 東日本, 西日本 } from "./pos-geoId-map";
import type { ProviderInfo } from "./types";

export const ProviderInfoList: ProviderInfo[] = [
  {
    name: "金沢ケーブル",
    domains: ["kanazawacable.jp", "spacelan.ne.jp"],
    geoIds: ["17"],
    url: "https://www.kanazawacable.jp/join/area/",
    description: "石川県のみ",
    coverage: "石川県",
  },
  {
    name: "メガエッグ",
    domains: ["megaegg.ne.jp"],
    geoIds: ["31", "32", "33", "34", "35"],
    url: "https://www.megaegg.jp/area/megaegg/?svc=1",
    description: "中国地方のみ",
    coverage: "中国地方",
  },
  {
    name: "吉備テレビ",
    domains: ["kibi.ne.jp"],
    geoIds: ["33"],
    url: "https://www.catv-jcta.jp/search/detail/10110371",
    description: "岡山県のみ",
    coverage: "岡山県",
  },
  {
    name: "トコちゃんねる静岡",
    domains: ["dws.ne.jp"],
    geoIds: ["220010"],
    url: "https://www.catv-jcta.jp/search/detail/10110216",
    description: "静岡県静岡市のみ",
    coverage: "静岡県静岡市",
  },
  {
    name: "across",
    domains: ["across.or.jp"],
    geoIds: ["22"],
    url: "https://www.across.or.jp/",
    coverage: "静岡県",
  },
  {
    name: "ピカラネット",
    domains: ["pikara.ne.jp"],
    geoIds: ["36", "37", "38", "39"],
    url: "https://www.pikara.jp/net/area.html",
    description: "四国地方のみ",
    coverage: "四国地方",
  },
  {
    name: "株式会社STNet",
    domains: ["stnet.ne.jp"],
    geoIds: ["36", "37", "38", "39"],
    url: "https://www.stnet.co.jp/",
    description: "ぴからの親っぽい",
    coverage: "四国地方",
  },
  {
    name: "BBIQ",
    domains: ["ppp.bbiq.jp"],
    geoIds: ["40", "41", "42", "43", "44", "45", "46"],
    url: "https://www.bbiq.jp/",
    description: "九州地方のみ",
    coverage: "九州地方",
  },
  {
    name: "東京ベイネットワーク",
    domains: ["baynet.jp"],
    geoIds: ["130010"],
    url: "https://www.catv-jcta.jp/search/detail/10110101",
    description: "東京都のみ",
    coverage: "東京都",
  },
  {
    name: "豊島ケーブルネットワーク",
    domains: ["toshima.ne.jp"],
    geoIds: ["130010"],
    url: "https://www.catv-jcta.jp/search/detail/10110103",
    description: "東京都のみ",
    coverage: "東京都",
  },
  {
    name: "ＴＯＫＡＩケーブルネットワーク",
    domains: ["thn.ne.jp"],
    geoIds: ["23"],
    url: "https://www.catv-jcta.jp/search/detail/10110219",
    description: "静岡県のみ",
    coverage: "静岡県",
  },
  {
    name: "いちはらケーブルテレビ",
    domains: ["icntv.ne.jp", "eastcom.ne.jp"],
    geoIds: ["120010"],
    url: "https://www.catv-jcta.jp/search/detail/10110117",
    description: "千葉県北西部のみ",
    coverage: "千葉県北西部",
  },
  {
    name: "イッツコム",
    domains: ["itscom.jp", "246.ne.jp"],
    geoIds: ["130010", "140010"],
    url: "https://www.itscom.co.jp/info/areamap/",
    coverage: "東京・神奈川",
  },
  {
    name: "愛媛ＣＡＴＶ",
    domains: ["e-catv.ne.jp"],
    geoIds: ["380010", "380030"],
    url: "https://www.catv-jcta.jp/search/detail/10110421",
    description: "愛媛の中予/南予のみ",
    coverage: "愛媛県中予/南予",
  },
  {
    name: "ニューメディア",
    domains: ["ncv.co.jp", "ncv.ne.jp", "ncv.jp", "omn.ne.jp", "tlp.ne.jp"],
    geoIds: ["017010", "060020", "070010", "150010"],
    url: "https://www.catv-jcta.jp/search/detail/10110047",
    description:
      "北海道函館市,北斗市,七飯町/山形県米沢市,南陽市,高畠町,川西町/福島県福島市/新潟県新潟市北区,新潟市東区,新潟市中央区,新潟市西区のみ",
    coverage:
      "北海道函館市,北斗市,七飯町/山形県米沢市,南陽市,高畠町,川西町/福島県福島市/新潟県新潟市北区,新潟市東区,新潟市中央区,新潟市西区",
  },
  {
    name: "ちゅピＣＯＭ",
    domains: ["fch.ne.jp", "hicat.ne.jp"],
    geoIds: ["34"],
    url: "https://www.catv-jcta.jp/search/detail/10110383",
    description: "広島県のみ",
    coverage: "広島県",
  },
  {
    name: "大分ケーブルテレコム",
    domains: ["octv.ne.jp", "oct-net.ne.jp"],
    geoIds: ["44"],
    url: "https://www.catv-jcta.jp/search/detail/10110486",
    description: "大分県のみ",
    coverage: "大分県",
  },
  {
    name: "飛騨高山ケーブルネットワーク",
    domains: ["hidatakayama.ne.jp"],
    geoIds: ["210020"],
    url: "https://www.catv-jcta.jp/search/detail/10112002",
    description: "岐阜県のみ",
    coverage: "岐阜県",
  },
  {
    name: "鳥取テレトピア",
    domains: ["inabapyonpyon.net"],
    geoIds: ["310010"],
    url: "https://www.catv-jcta.jp/search/detail/10110363",
    description: "鳥取県鳥取市のみ",
    coverage: "鳥取県鳥取市",
  },
  {
    name: "アイ・キャン",
    domains: ["icn-tv.ne.jp"],
    geoIds: ["350030"],
    url: "https://www.catv-jcta.jp/search/detail/10110391",
    description: "山口県東部のみ",
    coverage: "山口県東部",
  },
  {
    name: "アドバンスコープ",
    domains: ["asint.jp", "nava21.ne.jp"],
    geoIds: ["240010"],
    url: "https://www.catv-jcta.jp/search/detail/10110261",
    description: "三重県のみ",
    coverage: "三重県",
  },
  {
    name: "石見ケーブルビジョン",
    domains: ["iwamicatv.jp"],
    geoIds: ["320020"],
    url: "https://www.catv-jcta.jp/search/detail/10110368",
    description: "島根県のみ",
    coverage: "島根県",
  },
  {
    name: "周防ケーブルネット",
    domains: ["net-scn.jp"],
    geoIds: ["350030"],
    url: "https://www.catv-jcta.jp/search/detail/10112017",
    description: "山口県柳井市のみ",
    coverage: "山口県柳井市",
  },
  {
    name: "笠岡放送",
    domains: ["kcv.ne.jp"],
    geoIds: ["330010"],
    url: "https://www.catv-jcta.jp/search/detail/10110376",
    description: "岡山県のみ",
    coverage: "岡山県",
  },
  {
    name: "鹿沼ケーブルテレビ",
    domains: ["bc9.ne.jp"],
    geoIds: ["090010"],
    url: "https://www.catv-jcta.jp/search/detail/10110056",
    description: "栃木県鹿沼市のみ",
    coverage: "栃木県鹿沼市",
  },
  {
    name: "GLBB",
    domains: ["glbb.ne.jp"],
    geoIds: ["13", "14", "02", "47"],
    url: "https://www.glbb.jp/service/business/glbb-hikari/",
    description: "東京、神奈川、青森、沖縄らしい?",
    coverage: "東京、神奈川、青森、沖縄",
  },
  {
    name: "本庄ケーブルテレビ",
    domains: ["catnet.jp"],
    geoIds: ["110020"],
    url: "https://www.catv-jcta.jp/search/detail/10110076",
    description: "埼玉県のみ",
    coverage: "埼玉県",
  },
  {
    name: "わたらせテレビ",
    domains: ["watv.ne.jp"],
    geoIds: ["090010", "100010"],
    url: "https://www.catv-jcta.jp/search/detail/10112025",
    description: "栃木県、群馬県のみ",
    coverage: "栃木県足利市、群馬県太田市",
  },
  {
    name: "宇都宮ケーブルテレビ",
    domains: ["ucatv.ne.jp"],
    geoIds: ["090010"],
    url: "https://www.catv-jcta.jp/search/detail/10110055",
    description: "栃木県のみ",
    coverage: "栃木県",
  },
  {
    name: "浜松ケーブルテレビ",
    domains: ["winde.jp"],
    geoIds: ["220040"],
    url: "https://www.catv-jcta.jp/search/detail/10110223",
    coverage: "静岡県浜松市",
  },
  {
    name: "ＹＯＵテレビ",
    domains: ["netyou.jp"],
    geoIds: ["140010"],
    url: "https://www.catv-jcta.jp/search/detail/10110143",
    description: "神奈川県のみ",
    coverage: "神奈川県",
  },
  {
    name: "沖縄セルラー",
    domains: ["au-hikari.ne.jp"],
    geoIds: ["47"],
    url: "https://okinawa-cellular.jp/personal/hikari/",
    description: "沖縄県のみ",
    coverage: "沖縄県",
  },
  {
    name: "らーばんねっと",
    domains: ["rurbannet.ne.jp"],
    geoIds: ["120010"],
    url: "https://ja.wikipedia.org/wiki/%E3%82%89%E3%83%BC%E3%81%B0%E3%82%93%E3%81%AD%E3%81%A3%E3%81%A8#%E6%8F%90%E4%BE%9B%E5%8C%BA%E5%9F%9F%E5%86%85%E8%87%AA%E6%B2%BB%E4%BD%93",
    coverage: "千葉県 印西市 白井市 船橋市",
  },
  {
    name: "壱岐市ケーブルテレビ",
    domains: ["iq-hikari.jp"],
    geoIds: ["420030"],
    url: "https://www.catv-jcta.jp/search/detail/10112120",
    description: "長崎県壱岐市のみ",
    coverage: "長崎県壱岐市",
  },
  {
    name: "横浜ケーブルビジョン(株)",
    domains: ["catv-yokohama.ne.jp"],
    geoIds: ["140010"],
    url: "https://www.catv-jcta.jp/search/detail/10110144",
    description: "横浜市のみ",
    coverage: "横浜市",
  },
  {
    name: "(株)ケーブルテレビ佐伯",
    domains: ["cts-net.ne.jp"],
    geoIds: ["440040"],
    url: "https://www.catv-jcta.jp/search/detail/10110489",
    coverage: "大分県佐伯市",
  },
  {
    name: "井原放送(株)",
    domains: ["ibara.ne.jp"],
    geoIds: ["330010", "340010"],
    url: "https://www.catv-jcta.jp/search/detail/10110369",
    coverage: "岡山県井原市  広島県福山市",
  },
  {
    name: "上越ケーブルビジョン(株)",
    domains: ["joetsu.ne.jp"],
    geoIds: ["150030"],
    url: "https://www.catv-jcta.jp/search/detail/10110187",
    coverage: "新潟県妙高市上越市",
  },
  {
    name: "(株)シティーケーブル周南",
    domains: ["ccsnet.ne.jp"],
    geoIds: ["350020"],
    url: "https://www.catv-jcta.jp/search/detail/10110394",
    coverage: "山口県周南市",
  },
  {
    name: "仙台ＣＡＴＶ(株)",
    domains: ["cat-v.ne.jp"],
    geoIds: ["040010", "040020"],
    url: "https://www.catv-jcta.jp/search/detail/10110032",
    coverage: "宮城県仙台市/名取市",
  },
  {
    name: "(株)たけはらケーブルネットワーク",
    domains: ["tanet.ne.jp"],
    geoIds: ["340010"],
    url: "https://www.catv-jcta.jp/search/detail/10112052",
    coverage: "広島県竹原市",
  },
  {
    name: "射水ケーブルネットワーク(株)",
    domains: ["canet.ne.jp"],
    geoIds: ["160020"],
    url: "https://www.catv-jcta.jp/search/detail/10110274",
    coverage: "富山県高岡市射水市",
  },
  {
    name: "ジェイコム日野",
    domains: ["hinocatv.ne.jp"],
    geoIds: ["130010"],
    url: "https://ja.wikipedia.org/wiki/%E3%82%B8%E3%82%A7%E3%82%A4%E3%82%B3%E3%83%A0%E6%97%A5%E9%87%8E",
    description: "ジェイコム東京に吸収されたので東京で良い?",
    coverage: "東京都",
  },
  {
    name: "大同大学",
    domains: ["daido-it.ac.jp"],
    geoIds: ["230010"],
    url: "https://www.daido-it.ac.jp/outline/access/",
    coverage: "愛知県名古屋市",
  },
  {
    name: "千葉工業大学",
    domains: ["it-chiba.ac.jp"],
    geoIds: ["130010", "120010"],
    url: "https://www.it-chiba.ac.jp/institute/access/",
    coverage: "千葉県習志野市と東京都墨田区",
  },
  {
    name: "北見工業大学",
    domains: ["kitami-it.ac.jp"],
    geoIds: ["013010", "013020"],
    url: "https://www.kitami-it.ac.jp/access/",
    coverage: "北海道北見市",
  },
  {
    name: "久留米工業高等専門学校",
    domains: ["kurume-nct.ac.jp"],
    geoIds: ["400040"],
    url: "https://www.kurume-nct.ac.jp/kikaku/Access.html",
    coverage: "福岡県久留米市",
  },
  {
    name: "名古屋大学",
    domains: ["nagoya-u.ac.jp"],
    geoIds: ["230010"],
    url: "https://www.nagoya-u.ac.jp/contact/directions.html",
    coverage: "愛知県名古屋市",
  },
  {
    name: "東京工芸大学",
    domains: ["t-kougei.ac.jp"],
    geoIds: ["130010", "140020"],
    url: "https://www.t-kougei.ac.jp/",
    coverage: "東京都中野区と神奈川県厚木市",
  },
  {
    name: "東北大学",
    domains: ["tohoku.ac.jp"],
    geoIds: ["040010"],
    url: "https://www.tohoku.ac.jp/japanese/profile/campus/01/access/",
    coverage: "宮城県仙台市",
  },
  {
    name: "(株)倉敷ケーブルテレビ",
    domains: ["kct.ad.jp"],
    geoIds: ["330010"],
    url: "https://www.catv-jcta.jp/search/detail/10110372",
    coverage: "岡山県岡山市南区  倉敷市  玉野市  総社市  早島町",
  },
  {
    name: "(株)アミックスコム",
    domains: ["amixcom.jp"],
    geoIds: ["210010"],
    url: "https://www.catv-jcta.jp/search/detail/10110207",
    coverage: "岐阜県恵那市  輪之内町",
  },
  {
    name: "ＢＡＮ−ＢＡＮネットワークス(株)",
    domains: ["banban.jp"],
    geoIds: ["280010"],
    url: "https://www.catv-jcta.jp/search/detail/10110344",
    coverage: "兵庫県加古川市  高砂市  稲美町  播磨町",
  },
  {
    name: "ベイ・ウィング",
    domains: ["bwa.jp"],
    geoIds: ["280010", "260010", "270000"],
    url: "https://www.bwa.jp/service-charge/servicearea/",
    coverage:
      "兵庫県神戸市・芦屋市・宝塚市・川西市・明石市、京都府京都市・長岡京市・向日市・乙訓郡大山崎町、大阪府大阪市吹田市・茨木市・豊中市・池田市・摂津市・三島郡島本町",
  },
  {
    name: "ジェイコム千葉セントラル",
    domains: ["cnc.jp"],
    geoIds: ["120010"],
    url: "https://ja.wikipedia.org/wiki/%E3%82%B8%E3%82%A7%E3%82%A4%E3%82%B3%E3%83%A0%E5%8D%83%E8%91%89%E3%82%BB%E3%83%B3%E3%83%88%E3%83%A9%E3%83%AB",
    coverage: "千葉県千葉市",
  },
  {
    name: "成田ケーブルテレビ(株)",
    domains: ["nctv.co.jp"],
    geoIds: ["120010"],
    url: "https://www.catv-jcta.jp/search/detail/10110126",
    coverage: "千葉県成田市  富里市",
  },
  {
    name: "(株)四国中央テレビ",
    domains: ["cosmostv.jp"],
    geoIds: ["380020"],
    url: "https://www.catv-jcta.jp/search/detail/10110417",
    coverage: "愛媛県四国中央市",
  },
  {
    name: "(株)秋田ケーブルテレビ",
    domains: ["feba.jp", "cna.ne.jp"],
    geoIds: ["050010"],
    url: "https://www.catv-jcta.jp/search/detail/10110040",
    coverage: "秋田県秋田市  潟上市  三種町  五城目町",
  },
  {
    name: "雲南・飯南CATV",
    domains: ["iinan-net.jp"],
    geoIds: ["320010"],
    url: "https://www.unnan-yume.net/catv/service-net/net.php",
    coverage: "島根県雲南市・飯南町",
  },
  {
    name: "加賀ケーブル(株)",
    domains: ["kagacable.jp", "kagacable.ne.jp"],
    geoIds: ["170010"],
    url: "https://www.catv-jcta.jp/search/detail/10110280",
    coverage: "石川県加賀市",
  },
  {
    name: "ＫＣＶコミュニケーションズ(株)",
    domains: ["kcv.jp"],
    geoIds: ["440030"],
    url: "https://www.catv-jcta.jp/search/detail/10110488",
    coverage: "大分県日田市",
  },
  {
    name: "河口湖有線テレビ放送(有)",
    domains: ["lcnet.jp"],
    geoIds: ["190020"],
    url: "https://www.catv-jcta.jp/search/detail/10110150",
    coverage: "山梨県富士河口湖町",
  },
  {
    name: "能登町ケーブルテレビ",
    domains: ["luckynet.jp"],
    geoIds: ["170020"],
    url: "https://www.catv-jcta.jp/search/detail/10112130",
    coverage: "石川県能登町",
  },
  {
    name: "山陰ケーブルビジョン(株)",
    domains: ["mable.jp", "dojyokko.ne.jp", "mable.ne.jp"],
    geoIds: ["320010"],
    url: "https://www.catv-jcta.jp/search/detail/10110367",
    coverage: "島根県松江市  安来市",
  },
  {
    name: "ひとまろビジョン",
    domains: ["maro-v.jp"],
    geoIds: ["320020"],
    url: "https://www.maro-v.jp/~hitomaro/",
    coverage: "島根県益田市",
  },
  {
    name: "七尾ケーブルテレビ",
    domains: ["nanaonet.jp"],
    geoIds: ["170020"],
    url: "https://www.catv-jcta.jp/search/detail/10112007",
    coverage: "石川県七尾市",
  },
  {
    name: "(株)テレビ岸和田",
    domains: [
      "sensyu.ne.jp",
      "116-sensyu.ne.jp",
      "117-sensyu.ne.jp",
      "2-sensyu.ne.jp",
      "237-sensyu.ne.jp",
      "240-sensyu.ne.jp",
    ],
    geoIds: ["270000"],
    url: "https://www.catv-jcta.jp/search/detail/10110333",
    description:
      "sensyu.ne.jp以外のドメインは存在しないので逆引き設定多分ミスってる",
    coverage: "大阪府岸和田市  忠岡町",
  },
  {
    name: "(一財)研究学園都市コミュニティケーブルサービス",
    domains: ["accsnet.ne.jp"],
    geoIds: ["080020"],
    url: "https://www.catv-jcta.jp/search/detail/10110051",
    coverage: "茨城県つくば市",
  },
  {
    name: "青森ケーブルテレビ(株)",
    domains: ["actv.ne.jp"],
    geoIds: ["020010"],
    url: "https://www.catv-jcta.jp/search/detail/10110010",
    coverage: "青森県青森市",
  },
  {
    name: "株式会社ジェイコム足立",
    domains: ["adachi.ne.jp"],
    geoIds: ["130010"],
    url: "https://ja.wikipedia.org/wiki/%E3%82%B8%E3%82%A7%E3%82%A4%E3%82%B3%E3%83%A0%E8%B6%B3%E7%AB%8B",
    coverage: "東京都足立区",
  },
  {
    name: "aitai net",
    domains: ["aitai.ne.jp"],
    geoIds: ["230010", "230020", "210010", "210020"],
    url: "http://www.aitai.ne.jp/",
    coverage:
      "豊田市/みよし市/長久手市 蒲郡市/幸田町 多治見市/土岐市/瑞浪市 岐阜市/北方町/岐南町/笠松町 各務原市川島/羽島市/関市/美濃市 瑞穂市/山県市/下呂市",
  },
  {
    name: "株式会社アイティービー",
    domains: ["amigo.ne.jp", "amigo2.ne.jp"],
    geoIds: ["240020", "240010"],
    url: "https://ja.wikipedia.org/wiki/%E3%82%A2%E3%82%A4%E3%83%86%E3%82%A3%E3%83%BC%E3%83%93%E3%83%BC",
    coverage: "三重県伊勢市 度会郡 多気郡 志摩市 松阪市 南伊勢町",
  },
  {
    name: "あづみ野テレビ(株)",
    domains: ["anc-tv.ne.jp"],
    geoIds: ["200020", "200010"],
    url: "https://www.catv-jcta.jp/search/detail/10110165",
    coverage: "長野県松本市  安曇野市  池田町  松川村",
  },
  {
    name: "(株)あさがおテレビ",
    domains: ["asagaotv.ne.jp"],
    geoIds: ["170010"],
    url: "https://www.catv-jcta.jp/search/detail/10110283",
    coverage: "石川県白山市",
  },
  {
    name: "一般財団法人 阿蘇テレワークセンター",
    domains: ["aso.ne.jp"],
    geoIds: ["430020"],
    url: "https://hikari.aso.ne.jp/outline/",
    coverage: "熊本県阿蘇市産山村",
  },
  {
    name: "(株)ネット鹿島",
    domains: ["asunet.ne.jp"],
    geoIds: ["410010"],
    url: "https://www.catv-jcta.jp/search/detail/10110460",
    coverage: "佐賀県鹿島市",
  },
  {
    name: "テレビ阿波(株)",
    domains: ["awacco.ne.jp"],
    geoIds: ["360010"],
    url: "https://www.catv-jcta.jp/search/detail/10110414",
    coverage: "徳島県美馬市",
  },
  {
    name: "厚木伊勢原ケーブルネットワーク(株)",
    domains: ["ayu.ne.jp"],
    geoIds: ["140020"],
    url: "https://www.catv-jcta.jp/search/detail/10110130",
    coverage: "神奈川県厚木市",
  },
  {
    name: "(株)ベイ・コミュニケーションズ",
    domains: ["bai.ne.jp"],
    geoIds: ["270000", "280010"],
    url: "https://www.catv-jcta.jp/search/detail/10110350",
    coverage:
      "大阪府,兵庫県 神戸市北区  尼崎市  西宮市  伊丹市  宝塚市  川西市",
  },
  {
    name: "ＢＴＶ(株)",
    domains: ["btvm.ne.jp"],
    geoIds: ["450030", "450010", "460010", "460020"],
    url: "https://www.catv-jcta.jp/search/detail/10110496",
    coverage:
      "宮崎県都城市  日南市  小林市  三股町  高原町  鹿児島県鹿児島市  曽於市  志布志市",
  },
  {
    name: "佐賀シティビジョン(株)",
    domains: ["bunbun.ne.jp"],
    geoIds: ["410010"],
    url: "https://www.catv-jcta.jp/search/detail/10110456",
    coverage: "佐賀県佐賀市  小城市  神埼市  吉野ヶ里町",
  },
  {
    name: "山口ケーブルビジョン(株)",
    domains: ["c-able.ne.jp"],
    geoIds: ["350010", "350020", "350040"],
    url: "https://www.catv-jcta.jp/search/detail/10110397",
    coverage: "山口県宇部市  山口市  防府市  美祢市",
  },
  {
    name: "J:COM市川",
    domains: ["c3-net.ne.jp", "icnet.ne.jp"],
    geoIds: ["140010"],
    url: "https://ja.wikipedia.org/wiki/%E3%82%B8%E3%82%A7%E3%82%A4%E3%82%B3%E3%83%A0%E5%B8%82%E5%B7%9D",
    coverage: "横浜市",
  },
  {
    name: "(株)ケーブルワン",
    domains: ["cableone.ne.jp"],
    geoIds: ["410010"],
    url: "https://www.catv-jcta.jp/search/detail/10110454",
    coverage: "佐賀県武雄市  大町町  江北町  白石町",
  },
  {
    name: "(株)ＣＡＣ",
    domains: ["cac-net.ne.jp"],
    geoIds: ["230010"],
    url: "https://www.catv-jcta.jp/search/detail/10110234",
    coverage: "愛知県半田市  阿久比町  武豊町",
  },
  {
    name: "(株)広域高速ネット二九六",
    domains: ["catv296.ne.jp"],
    geoIds: ["120010", "120020"],
    url: "https://www.catv-jcta.jp/search/detail/10110127",
    coverage:
      "千葉県千葉市花見川区  千葉市若葉区  千葉市緑区  茂原市  成田市  佐倉市  東金市  四街道市  八街市  印西市  富里市  香取市  山武市  大網白里市  酒々井町  栄町  神崎町",
  },
  {
    name: "(株)ダイバーシティメディア",
    domains: ["catvy.ne.jp"],
    geoIds: ["060010"],
    url: "https://www.catv-jcta.jp/search/detail/10110045",
    coverage: "山形県山形市  天童市  山辺町",
  },
  {
    name: "ケーブルテレビ(株)",
    domains: ["cc9.ne.jp"],
    geoIds: ["080020", "090010", "100010"],
    url: "https://www.catv-jcta.jp/search/detail/10110059",
    coverage:
      "茨城県結城市  筑西市 栃木県栃木市  下野市  上三川町  壬生町 群馬県館林市  板倉町  明和町  千代田町  邑楽町",
  },
  {
    name: "(株)ケーブル・ジョイ",
    domains: ["ccjnet.ne.jp"],
    geoIds: ["340010"],
    url: "https://www.catv-jcta.jp/search/detail/10110382",
    coverage: "広島県福山市  府中市  神石高原町",
  },
  {
    name: "ＣＣＮｅｔ(株)",
    domains: ["ccnet-ai.ne.jp", "ccnet.ne.jp", "ccnw.ne.jp", "ccnetmie.ne.jp"],
    geoIds: ["210010", "230010", "230020", "240010"],
    url: "https://www.catv-jcta.jp/search/detail/10110239",
    coverage:
      "岐阜県美濃加茂市  各務原市  本巣市  養老町  川辺町  八百津町  白川町、愛知県名古屋市緑区  春日井市  豊川市  犬山市  小牧市  豊明市  日進市  東郷町  大口町  扶桑町、三重県桑名市  朝日町  川越町",
  },
  {
    name: "(株)中海テレビ放送",
    domains: ["chukai.ne.jp"],
    geoIds: ["310020"],
    url: "https://www.catv-jcta.jp/search/detail/10110361",
    coverage:
      "鳥取県米子市  境港市  日吉津村  大山町  南部町  伯耆町  日南町  日野町",
  },
  {
    name: "西尾張シーエーティーヴィ(株)",
    domains: ["clovernet.ne.jp"],
    geoIds: ["230010"],
    url: "https://www.catv-jcta.jp/search/detail/10110243",
    coverage:
      "愛知県津島市  稲沢市  愛西市  清須市  弥富市  あま市  大治町  蟹江町",
  },
  {
    name: "(株)長崎ケーブルメディア",
    domains: ["cncm.ne.jp"],
    geoIds: ["420010"],
    url: "https://www.catv-jcta.jp/search/detail/10110475",
    coverage: "長崎県長崎市  西海市  長与町  時津町",
  },
  {
    name: "能越ケーブルネット(株)",
    domains: ["cnh.ne.jp"],
    geoIds: ["160020", "170020"],
    url: "https://www.catv-jcta.jp/search/detail/10110273",
    coverage: "富山県氷見市、石川県珠洲市  羽咋市  穴水町",
  },
  {
    name: "ケーブルステーション福岡",
    domains: ["csf.ne.jp"],
    geoIds: ["400010", "400030"],
    url: "https://csf.ne.jp/service_area/",
    coverage:
      "福岡県 春日市 大野城市 太宰府市 那珂川市 筑紫野市 宇美町 志免町 須恵町 粕屋町 嘉麻市",
  },
  {
    name: "ＣＴＢメディア(株)",
    domains: ["ctb.ne.jp"],
    geoIds: ["440010"],
    url: "https://www.catv-jcta.jp/search/detail/10110490",
    coverage: "大分県 別府市  日出町",
  },
  {
    name: "(株)ケーブルテレビ可児",
    domains: ["ctk.ne.jp"],
    geoIds: ["210010"],
    url: "https://www.catv-jcta.jp/search/detail/10110203",
    coverage: "岐阜県 可児市  御嵩町",
  },
  {
    name: "(株)ケーブルテレビ富山",
    domains: ["ctt.ne.jp"],
    geoIds: ["160010"],
    url: "https://www.catv-jcta.jp/search/detail/10110271",
    coverage: "富山県 富山市  舟橋村",
  },
  {
    name: "(株)シー・ティー・ワイ",
    domains: ["cty-net.ne.jp"],
    geoIds: ["240010"],
    url: "https://www.catv-jcta.jp/search/detail/10110258",
    coverage: "三重県 四日市市  桑名市  いなべ市  木曽岬町  菰野町",
  },
  {
    name: "(有)峡西シーエーテーブイ",
    domains: ["cvk.ne.jp"],
    geoIds: ["190010"],
    url: "https://www.catv-jcta.jp/search/detail/10110152",
    coverage: "山梨県 南アルプス市",
  },
  {
    name: "福井ケーブルテレビ(株)",
    domains: ["fctv.ne.jp"],
    geoIds: ["180010"],
    url: "https://www.catv-jcta.jp/search/detail/10110289",
    coverage: "福井県 福井市  永平寺町  池田町  南越前町",
  },
  {
    name: "山梨ＣＡＴＶ(株)",
    domains: ["fruits.ne.jp"],
    geoIds: ["190010"],
    url: "https://www.catv-jcta.jp/search/detail/10110159",
    coverage: "山梨県 山梨市",
  },
  {
    name: "グリーンシティケーブルテレビ(株)",
    domains: ["gctv.ne.jp"],
    geoIds: ["230010"],
    url: "https://www.catv-jcta.jp/search/detail/10110233",
    coverage: "愛知県 名古屋市守山区  瀬戸市  尾張旭市",
  },
  {
    name: "(株)五島テレビ",
    domains: ["goto-tv.ne.jp"],
    geoIds: ["420040"],
    url: "https://www.catv-jcta.jp/search/detail/10112026",
    coverage: "長崎県 五島市",
  },
  {
    name: "郡上ケーブルテレビ放送センター",
    domains: ["gujo-tv.ne.jp"],
    geoIds: ["210010"],
    url: "https://www.catv-jcta.jp/search/detail/10110206",
    coverage: "岐阜県 郡上市",
  },
  {
    name: "伊万里ケーブルテレビジョン(株)",
    domains: ["hachigamenet.ne.jp"],
    geoIds: ["410020"],
    url: "https://www.catv-jcta.jp/search/detail/10110451",
    coverage: "佐賀県 伊万里市",
  },
  {
    name: "藤津ケーブルビジョン(株)",
    domains: ["hagakure.ne.jp"],
    geoIds: ["410010"],
    url: "https://www.catv-jcta.jp/search/detail/10110461",
    coverage: "佐賀県 小城市  嬉野市  太良町",
  },
  {
    name: "萩テレビ(株)",
    domains: ["haginet.ne.jp"],
    geoIds: ["320020", "350040"],
    url: "https://www.catv-jcta.jp/search/detail/10112189",
    coverage: "島根県 益田市、山口県 萩市  阿武町",
  },
  {
    name: "東松山ケーブルテレビ(株)",
    domains: ["hctv.ne.jp"],
    geoIds: ["110020"],
    url: "https://www.catv-jcta.jp/search/detail/10110079",
    coverage: "埼玉県 東松山市  滑川町",
  },
  {
    name: "(株)ひまわりてれび",
    domains: ["himawarinet.ne.jp"],
    geoIds: ["420010"],
    url: "https://www.catv-jcta.jp/search/detail/10110476",
    coverage: "長崎県 島原市  雲仙市  南島原市",
  },
  {
    name: "(株)伊豆急ケーブルネットワーク",
    domains: ["i-younet.ne.jp"],
    geoIds: ["140020", "220020"],
    url: "https://www.catv-jcta.jp/search/detail/10110210",
    coverage: "神奈川県 湯河原町、静岡県 熱海市  伊東市  下田市  東伊豆町",
  },
  {
    name: "伊賀上野ケーブルテレビ(株)",
    domains: ["ict.ne.jp"],
    geoIds: ["240010"],
    url: "https://www.catv-jcta.jp/search/detail/10110255",
    coverage: "三重県 伊賀市",
  },
  {
    name: "入間ケーブルテレビ(株)",
    domains: ["ictv.ne.jp"],
    geoIds: ["110010", "130010"],
    url: "https://www.catv-jcta.jp/search/detail/10110065",
    coverage: "埼玉県 入間市、東京都 瑞穂町",
  },
  {
    name: "諫早ケーブルメディア(株)",
    domains: ["icv-net.ne.jp"],
    geoIds: ["420010"],
    url: "https://www.catv-jcta.jp/search/detail/10110465",
    coverage: "長崎県 長崎市  諫早市  雲仙市",
  },
  {
    name: "ii-okinawa",
    domains: ["ii-okinawa.ne.jp"],
    geoIds: ["47"],
    url: "https://www.ii-okinawa.ad.jp/",
    coverage: "沖縄県",
  },
  {
    name: "黒潮町CATV",
    domains: ["iwk.ne.jp"],
    geoIds: ["390030"],
    url: "https://www.catv-jcta.jp/search/detail/10112135",
    coverage: "高知県 黒潮町",
  },
  {
    name: "(株)ＪＷＡＹ",
    domains: ["jway.ne.jp"],
    geoIds: ["080010"],
    url: "https://www.catv-jcta.jp/search/detail/10110054",
    coverage: "茨城県 日立市  ひたちなか市  東海村",
  },
  {
    name: "(株)キャッチネットワーク",
    domains: ["katch.ne.jp"],
    geoIds: ["230010"],
    url: "https://www.catv-jcta.jp/search/detail/10110232",
    coverage: "愛知県 碧南市  刈谷市  安城市  西尾市  知立市  高浜市",
  },
  {
    name: "近鉄ケーブルネットワーク(株)",
    domains: ["kcn.ne.jp"],
    geoIds: ["290010", "290020"],
    url: "https://www.catv-jcta.jp/search/detail/10110355",
    coverage:
      "奈良県 奈良市  大和高田市  大和郡山市  天理市  橿原市  桜井市  五條市  御所市  生駒市  香芝市  葛城市  宇陀市  山添村  平群町  三郷町  斑鳩町  安堵町  川西町  三宅町  田原本町  曽爾村  御杖村  高取町  明日香村  上牧町  王寺町  広陵町  河合町  吉野町  大淀町  下市町  黒滝村  天川村",
  },
  {
    name: "神河町ケーブルテレビネットワーク",
    domains: ["kcni.ne.jp"],
    geoIds: ["280010"],
    url: "https://www.catv-jcta.jp/search/detail/10110345",
    coverage: "兵庫県 神河町",
  },
  {
    name: "(株)ＫＣＮ京都",
    domains: ["kinet-tv.ne.jp"],
    geoIds: ["260010"],
    url: "https://www.catv-jcta.jp/search/detail/10110310",
    coverage: "京都府 宇治市  城陽市  京田辺市  木津川市  久御山町  精華町",
  },
  {
    name: "ジェイコム東京北",
    domains: ["kitanet.ne.jp"],
    geoIds: ["130010"],
    url: "https://ja.wikipedia.org/wiki/%E3%82%B8%E3%82%A7%E3%82%A4%E3%82%B3%E3%83%A0%E6%9D%B1%E4%BA%AC%E5%8C%97",
    coverage: "東京都北区",
  },
  {
    name: "ジェイコム東葛葛飾",
    domains: ["koalanet.ne.jp"],
    geoIds: ["120010", "130010"],
    url: "https://ja.wikipedia.org/wiki/%E3%82%B8%E3%82%A7%E3%82%A4%E3%82%B3%E3%83%A0%E6%9D%B1%E8%91%9B%E8%91%9B%E9%A3%BE",
    coverage: "千葉県 流山市 野田市 松戸市、東京都 葛飾区",
  },
  {
    name: "(株)テレビ九州",
    domains: ["ktknet.ne.jp"],
    geoIds: ["410010"],
    url: "https://www.catv-jcta.jp/search/detail/10110459",
    coverage: "佐賀県 武雄市  嬉野市",
  },
  {
    name: "Ｋビジョン(株)",
    domains: ["kvision.ne.jp"],
    geoIds: ["350020", "350030"],
    url: "https://www.catv-jcta.jp/search/detail/10110392",
    coverage: "山口県 下松市  光市  周南市  上関町  平生町",
  },
  {
    name: "旭川ケーブルテレビ(株)",
    domains: ["lan-do.ne.jp"],
    geoIds: ["012010"],
    url: "https://www.catv-jcta.jp/search/detail/10110002",
    coverage: "北海道 旭川市  鷹栖町  東神楽町  当麻町  比布町  愛別町  東川町",
  },
  {
    name: "(株)ＭＣＡＴ",
    domains: ["mcat.ne.jp"],
    geoIds: ["340010"],
    url: "https://www.catv-jcta.jp/search/detail/10110388",
    coverage: "広島県 三原市  世羅町",
  },
  {
    name: "南九州ケーブルテレビネット(株)",
    domains: ["mct.ne.jp"],
    geoIds: ["460010"],
    url: "https://www.catv-jcta.jp/search/detail/10110505",
    coverage: "鹿児島県 霧島市  姶良市",
  },
  {
    name: "松阪ケーブルテレビ・ステーション(株)",
    domains: ["mctv.ne.jp"],
    geoIds: ["240010", "240020"],
    url: "https://www.catv-jcta.jp/search/detail/10110262",
    coverage: "三重県 松阪市  志摩市  多気町  明和町  大台町  大紀町",
  },
  {
    name: "(株)ケーブルネット鈴鹿",
    domains: ["mecha.ne.jp"],
    geoIds: ["240010"],
    url: "https://www.catv-jcta.jp/search/detail/10110257",
    coverage: "三重県 鈴鹿市",
  },
  {
    name: "知多メディアスネットワーク(株)",
    domains: ["medias.ne.jp"],
    geoIds: ["230010"],
    url: "https://www.catv-jcta.jp/search/detail/10110238",
    coverage: "愛知県 東海市  大府市  知多市  東浦町",
  },
  {
    name: "ミクスネットワーク(株)",
    domains: ["mics.ne.jp"],
    geoIds: ["230010"],
    url: "https://www.catv-jcta.jp/search/detail/10110244",
    coverage: "愛知県 岡崎市",
  },
  {
    name: "新川地域介護保険・ケーブルテレビ事業組合",
    domains: ["milale.ne.jp"],
    geoIds: ["160010"],
    url: "https://www.catv-jcta.jp/search/detail/10112163",
    coverage: "富山県 黒部市  入善町  朝日町",
  },
  {
    name: "宮崎ケーブルテレビ(株)",
    domains: ["miyazaki-catv.ne.jp"],
    geoIds: ["450010", "450020"],
    url: "https://www.catv-jcta.jp/search/detail/10110497",
    coverage: "宮崎県 宮崎市  西都市  国富町  綾町  高鍋町  新富町",
  },
  {
    name: "美方ケーブルネットワーク(株)",
    domains: ["mmnet-ai.ne.jp"],
    geoIds: ["180020"],
    url: "https://www.catv-jcta.jp/search/detail/10110290",
    coverage: "福井県 美浜町  若狭町",
  },
  {
    name: "(株)エヌ・シィ・ティ",
    domains: ["nct9.ne.jp"],
    geoIds: ["150020", "150010"],
    url: "https://www.catv-jcta.jp/search/detail/10110188",
    coverage: "新潟県 長岡市  三条市  柏崎市  小千谷市  見附市  燕市",
  },
  {
    name: "沖縄ケーブルネットワーク(株)",
    domains: ["nirai.ne.jp"],
    geoIds: ["471010"],
    url: "https://www.catv-jcta.jp/search/detail/10110509",
    coverage:
      "沖縄県 那覇市  宜野湾市  浦添市  沖縄市  豊見城市  北谷町  北中城村  西原町  南風原町",
  },
  {
    name: "(株)日本ネットワークサービス",
    domains: ["nns.ne.jp"],
    geoIds: ["190010"],
    url: "https://www.catv-jcta.jp/search/detail/10110157",
    coverage:
      "山梨県 甲府市  韮崎市  南アルプス市  北杜市  甲斐市  笛吹市  中央市  市川三郷町  身延町  昭和町",
  },
  {
    name: "おおむらケーブルテレビ(株)",
    domains: ["octp-net.ne.jp"],
    geoIds: ["420010"],
    url: "https://www.catv-jcta.jp/search/detail/10110467",
    coverage: "長崎県 大村市",
  },
  {
    name: "(株)大垣ケーブルテレビ",
    domains: ["ogaki-tv.ne.jp"],
    geoIds: ["210010"],
    url: "https://www.catv-jcta.jp/search/detail/10110201",
    coverage:
      "岐阜県 大垣市  海津市  垂井町  関ケ原町  神戸町  揖斐川町  池田町",
  },
  {
    name: "奥出雲町CATV",
    domains: ["okuizumo.ne.jp"],
    geoIds: ["320010"],
    url: "https://www.catv-jcta.jp/search/detail/10112080",
    coverage: "島根県 奥出雲町",
  },
  {
    name: "岡山ネットワーク(株)",
    domains: ["oninet.ne.jp"],
    geoIds: ["330010", "330020"],
    url: "https://www.catv-jcta.jp/search/detail/10110370",
    coverage: "岡山県 岡山市北区  岡山市中区  岡山市東区  岡山市南区  久米南町",
  },
  {
    name: "(株)アイ・シー・シー",
    domains: ["orihime.ne.jp"],
    geoIds: ["230010"],
    url: "https://www.catv-jcta.jp/search/detail/10110230",
    coverage: "愛知県 一宮市",
  },
  {
    name: "(株)ぴーぷる",
    domains: ["people-i.ne.jp"],
    geoIds: ["410020"],
    url: "https://www.catv-jcta.jp/search/detail/10110453",
    coverage: "佐賀県 唐津市",
  },
  {
    name: "(株)三次ケーブルビジョン",
    domains: ["pionet.ne.jp"],
    geoIds: ["340020"],
    url: "https://www.catv-jcta.jp/search/detail/10112004",
    coverage: "広島県 三次市",
  },
  {
    name: "(株)嶺南ケーブルネットワーク",
    domains: ["rcn.ne.jp"],
    geoIds: ["180020"],
    url: "https://www.catv-jcta.jp/search/detail/10110292",
    coverage: "福井県 敦賀市",
  },
  {
    name: "J:COM 港・新宿",
    domains: ["rosenet.ne.jp"],
    geoIds: ["130010"],
    url: "https://ja.wikipedia.org/wiki/J:COM_%E6%B8%AF%E3%83%BB%E6%96%B0%E5%AE%BF",
    coverage: "東京都 港区 新宿区",
  },
  {
    name: "琉球コミュニケーションズ",
    domains: ["ryucom.ne.jp"],
    geoIds: ["47"],
    url: "http://www.ryucom.ne.jp/",
    coverage: "沖縄",
  },
  {
    name: "湘南ケーブルネットワーク(株)",
    domains: ["scn-net.ne.jp"],
    geoIds: ["140010", "140020"],
    url: "https://www.catv-jcta.jp/search/detail/10110139",
    coverage: "神奈川県 平塚市  大磯町  二宮町  中井町  大井町  松田町",
  },
  {
    name: "スターキャット(株)",
    domains: ["starcat.ne.jp"],
    geoIds: ["230010"],
    url: "https://www.catv-jcta.jp/search/detail/10110236",
    coverage:
      "愛知県 名古屋市千種区  名古屋市東区  名古屋市北区  名古屋市西区  名古屋市中村区  名古屋市中区  名古屋市昭和区  名古屋市瑞穂区  名古屋市熱田区  名古屋市中川区  名古屋市港区  名古屋市南区  名古屋市名東区  名古屋市天白区  江南市  岩倉市  清須市  北名古屋市  豊山町",
  },
  {
    name: "知多半島ケーブルネットワーク(株)",
    domains: ["tac-net.ne.jp"],
    geoIds: ["230010"],
    url: "https://www.catv-jcta.jp/search/detail/10110240",
    coverage: "愛知県 常滑市  南知多町  美浜町  武豊町",
  },
  {
    name: "玉島テレビ放送(株)",
    domains: ["tamatele.ne.jp"],
    geoIds: ["330010"],
    url: "https://www.catv-jcta.jp/search/detail/10110374",
    coverage: "岡山県 倉敷市",
  },
  {
    name: "東京ケーブルネットワーク(株)",
    domains: ["tcn-catv.ne.jp"],
    geoIds: ["130010"],
    url: "https://www.catv-jcta.jp/search/detail/10110097",
    coverage: "東京都 千代田区  中央区  文京区  荒川区",
  },
  {
    name: "高岡ケーブルネットワーク(株)",
    domains: ["tcnet.ne.jp"],
    geoIds: ["160020"],
    url: "https://www.catv-jcta.jp/search/detail/10110275",
    coverage: "富山県 高岡市",
  },
  {
    name: "豊橋ケーブルネットワーク(株)",
    domains: ["tees.ne.jp"],
    geoIds: ["230010"],
    url: "https://www.catv-jcta.jp/search/detail/10110241",
    coverage: "愛知県 豊橋市  新城市  田原市",
  },
  {
    name: "TOKAIネットワーククラブ",
    domains: ["tnc.ne.jp", "tokai.or.jp"],
    geoIds: ["22"],
    url: "https://faq.tokai-grp.jp/tnc/web/Search.aspx?Category=3498",
    coverage: "静岡県",
  },
  {
    name: "鳥取中央有線放送(株)",
    domains: ["torichu.ne.jp"],
    geoIds: ["310020"],
    url: "https://www.catv-jcta.jp/search/detail/10110362",
    coverage: "鳥取県 湯梨浜町  琴浦町  北栄町",
  },
  {
    name: "こしの都ネットワーク(株)",
    domains: ["ttn.ne.jp"],
    geoIds: ["180010"],
    url: "https://www.catv-jcta.jp/search/detail/10110288",
    coverage: "福井県 鯖江市  越前市  越前町",
  },
  {
    name: "(株)多摩テレビ",
    domains: ["ttv.ne.jp"],
    geoIds: ["130010"],
    url: "https://www.catv-jcta.jp/search/detail/10110094",
    coverage: "東京都 八王子市  町田市  多摩市  稲城市",
  },
  {
    name: "(株)テレビ小松",
    domains: ["tvk.ne.jp"],
    geoIds: ["170010"],
    url: "https://www.catv-jcta.jp/search/detail/10110282",
    coverage: "石川県 小松市  能美市",
  },
  {
    name: "(株)テレビ松本ケーブルビジョン",
    domains: ["tvm.ne.jp"],
    geoIds: ["200020"],
    url: "https://www.catv-jcta.jp/search/detail/10110180",
    coverage: "長野県 松本市  塩尻市  山形村  朝日村",
  },
  {
    name: "(株)上田ケーブルビジョン",
    domains: ["ueda.ne.jp"],
    geoIds: ["200020", "200010"],
    url: "https://www.catv-jcta.jp/search/detail/10110171",
    coverage: "長野県 上田市  東御市  青木村  坂城町",
  },
  {
    name: "(株)ケーブルメディアワイワイ",
    domains: ["wainet.ne.jp"],
    geoIds: ["450020", "450040"],
    url: "https://www.catv-jcta.jp/search/detail/10110495",
    coverage:
      "宮崎県 延岡市  日向市  川南町  都農町  門川町  美郷町  高千穂町  日之影町",
  },
  {
    name: "蕨ケーブルビジョン(株)",
    domains: ["warabi.ne.jp"],
    geoIds: ["110010"],
    url: "https://www.catv-jcta.jp/search/detail/10110078",
    coverage: "埼玉県 蕨市",
  },
  {
    name: "ウィルビーエス",
    domains: ["wbs.ne.jp"],
    geoIds: ["22"],
    url: "https://www.wbs.ne.jp/topic/move/#1",
    coverage: "静岡県",
  },
  {
    name: "姫路ケーブルテレビ(株)",
    domains: ["winknet.ne.jp"],
    geoIds: ["280010"],
    url: "https://www.catv-jcta.jp/search/detail/10110351",
    coverage: "兵庫県 姫路市  加西市  宍粟市  たつの市  太子町  上郡町  佐用町",
  },
  {
    name: "ゆずの里ケーブルテレビ(株)",
    domains: ["yuzu-tv.ne.jp"],
    geoIds: ["110010"],
    url: "https://www.catv-jcta.jp/search/detail/10112056",
    coverage: "埼玉県 毛呂山町",
  },
  {
    name: "ZTV",
    domains: ["ztv.ne.jp"],
    geoIds: [
      "240010",
      "240020",
      "250020",
      "250010",
      "300020",
      "300010",
      "260010",
    ],
    url: "https://www.ztv.co.jp/",
    coverage:
      "三重県 津市 松阪市 亀山市 尾鷲市 北牟婁郡紀北町 熊野市 南牟婁郡御浜町 紀宝町 伊勢市 鳥羽市 志摩市 度会郡玉城町 度会町 南伊勢町、滋賀県 彦根市 長浜市 米原市 高島市 大津市 草津市 守山市 栗東市 野洲市 湖南市 近江八幡市 蒲生郡竜王町、和歌山県 新宮市 田辺市 東牟婁郡串本町 那智勝浦町 太地町 古座川町 北山村 日高郡日高町 由良町 日高川町 有田郡広川町、京都府 京都市西京区 亀岡市 船井郡京丹波町",
  },
  {
    name: "(株)サイバーリンクス",
    domains: ["aikis.or.jp"],
    geoIds: ["300010"],
    url: "https://www.catv-jcta.jp/search/detail/10110357",
    coverage: "和歌山県 田辺市",
  },
  {
    name: "佐野ケーブルテレビ(株)",
    domains: ["sctv.jp"],
    geoIds: ["090010"],
    url: "https://www.catv-jcta.jp/search/detail/10110057",
    coverage: "栃木県 佐野市",
  },
  {
    name: "(株)上野原ブロードバンドコミュニケーションズ",
    domains: ["ubcnet.jp"],
    geoIds: ["190020"],
    url: "https://www.catv-jcta.jp/search/detail/10110160",
    coverage: "山梨県 上野原市",
  },
  {
    name: "愛知工業大学",
    domains: ["aitech.ac.jp"],
    geoIds: ["230010", "230020"],
    url: "https://www.aitech.ac.jp/",
    coverage: "愛知県名古屋市/豊田市",
  },
  {
    name: "東京電機大学",
    domains: ["dendai.ac.jp"],
    geoIds: ["130010", "110020", "120010"],
    url: "https://www.dendai.ac.jp/",
    coverage: "東京都足立区,埼玉県比企郡鳩山町,千葉県印西市",
  },
  {
    name: "東京芸術大学",
    domains: ["geidai.ac.jp"],
    geoIds: ["130010", "080020", "140010"],
    url: "https://www.geidai.ac.jp/",
    coverage: "東京都台東区,東京都足立区,茨城県取手市,神奈川県横浜市中区",
  },
  {
    name: "広島大学",
    domains: ["hiroshima-u.ac.jp"],
    geoIds: ["340010"],
    url: "https://www.hiroshima-u.ac.jp/",
    coverage: "広島県東広島市,広島市南区,広島市中区",
  },
  {
    name: "北陸先端科学技術大学院大学",
    domains: ["jaist.ac.jp"],
    geoIds: ["170010", "130010"],
    url: "https://www.jaist.ac.jp/index.html",
    coverage: "石川県能美市,石川県金沢市,東京都港区",
  },
  {
    name: "関東学院大学",
    domains: ["kanto-gakuin.ac.jp"],
    geoIds: ["140010"],
    url: "https://univ.kanto-gakuin.ac.jp/",
    coverage: "神奈川県横浜市",
  },
  {
    name: "慶應義塾大学",
    domains: ["keio.ac.jp"],
    geoIds: ["130010", "140010", "110010", "270000", "060030"],
    url: "https://www.keio.ac.jp/ja/",
    coverage:
      "東京都,神奈川県横浜市,神奈川県藤沢市,埼玉県さいたま市,神奈川県川崎市,山形県鶴岡市,大阪市",
  },
  {
    name: "京都精華大学",
    domains: ["kyoto-seika.ac.jp"],
    geoIds: ["260010"],
    url: "https://www.kyoto-seika.ac.jp/",
    coverage: "京都府京都市",
  },
  {
    name: "日本工業大学",
    domains: ["nit.ac.jp"],
    geoIds: ["110010"],
    url: "https://www.nit.ac.jp/",
    coverage: "埼玉県南埼玉郡宮代町",
  },
  {
    name: "沼津工業高等専門学校",
    domains: ["numazu-ct.ac.jp"],
    geoIds: ["220030"],
    url: "https://www.numazu-ct.ac.jp/",
    coverage: "静岡県沼津市",
  },
  {
    name: "大阪工業大学",
    domains: ["oit.ac.jp"],
    geoIds: ["270000"],
    url: "https://www.oit.ac.jp/index.html",
    coverage: "大阪府大阪市",
  },
  {
    name: "和歌山大学",
    domains: ["wakayama-u.ac.jp"],
    geoIds: ["300010"],
    url: "https://www.wakayama-u.ac.jp/",
    coverage: "和歌山県和歌山市",
  },
  {
    name: "山梨大学",
    domains: ["yamanashi.ac.jp"],
    geoIds: ["190010"],
    url: "https://www.yamanashi.ac.jp/",
    coverage: "山梨県甲府市,中央市",
  },
  {
    name: "中部テレコミュニケーション",
    domains: ["ctc.ad.jp"],
    geoIds: ["23", "21", "24", "22", "20"],
    url: "https://www.ctc.co.jp/",
    coverage: "愛知,岐阜,三重,静岡,長野",
  },
  {
    name: "エクストライド",
    domains: ["extride.ad.jp"],
    geoIds: ["430040"],
    url: "https://www.extride.ad.jp/",
    coverage: "熊本県人吉市",
  },
  {
    name: "BB.にいがた",
    domains: ["bb-niigata.jp"],
    geoIds: ["15"],
    url: "https://bb-niigata.jp",
    coverage: "新潟",
  },
  {
    name: "株式会社エックス・チェンジ",
    domains: ["ix1.co.jp"],
    geoIds: ["15"],
    description: "新潟っぽい",
    url: "https://www.ncom.ad.jp/overview.htm",
    coverage: "新潟",
  },
  {
    name: "オプテージ",
    domains: ["dsn.jp"],
    geoIds: ["25", "26", "27", "28", "29", "30"],
    description: "EO光の運営会社なので一旦EO光と同じエリアにしておく",
    url: "https://optage.co.jp/",
    coverage: "関西地方",
  },
  {
    name: "J:COM系",
    domains: ["j-cnet.jp"],
    geoIds: ["10", "11", "12", "13", "14"],
    description: "ホスト名的に関東近辺だと思われる",
    url: "https://www.jcom.co.jp/",
    coverage: "関東近辺",
  },
  {
    name: "カピバラクオリティ",
    domains: ["kapi-q.jp"],
    geoIds: ["330010"],
    url: "https://kapi-q.jp/",
    coverage: "岡山県倉敷市",
  },
  {
    name: "宮古テレビ(株)",
    domains: ["miyako-ma.jp"],
    geoIds: ["473000"],
    url: "https://www.catv-jcta.jp/search/detail/10110510",
    coverage: "沖縄県宮古島市  多良間村",
  },
  {
    name: "東白川ＣＡＴＶ（東白川村）",
    domains: ["50913.ne.jp"],
    geoIds: ["210010"],
    url: "https://www.catv-jcta.jp/search/detail/10112084",
    coverage: "岐阜県東白川村",
  },
  {
    name: "特定非営利活動法人ゆーとぴあネット",
    domains: ["akita-uruwashi.ne.jp"],
    geoIds: ["05"],
    url: "http://y-hikari.yutopia.or.jp/",
    coverage: "秋田県",
  },
  {
    name: "avis",
    domains: ["avis.ne.jp"],
    geoIds: ["200010", "200020"],
    url: "https://www.avis.ne.jp/",
    coverage: "長野市,上田市 ,大町市",
  },
  {
    name: "ケーブルネット埼玉株式会社",
    domains: ["cablenet.ne.jp"],
    geoIds: ["110010"],
    url: "https://ja.wikipedia.org/wiki/%E3%82%B8%E3%82%A7%E3%82%A4%E3%82%B3%E3%83%A0%E5%B7%9D%E5%8F%A3%E6%88%B8%E7%94%B0",
    coverage: "埼玉県 川口市 戸田市",
  },
  {
    name: "(株)ケーブルテレビ若狭小浜",
    domains: ["cho.ne.jp"],
    geoIds: ["180020"],
    url: "https://www.catv-jcta.jp/search/detail/10110293",
    coverage: "福井県小浜市",
  },
  {
    name: "マジカルサイト・インターネットサービス dokidoki!",
    domains: ["dokidoki.ne.jp"],
    geoIds: ["38"],
    url: "http://www.dokidoki.ne.jp/",
    description: "愛媛周辺らしい",
    coverage: "愛媛周辺",
  },
  {
    name: "EditNet",
    domains: ["edit.ne.jp"],
    geoIds: ["130010"],
    url: "https://www.editnet.ad.jp/services/",
    coverage: "東京周辺",
  },
  {
    name: "富士川シーエーティーヴィ(株)",
    domains: ["fb-net.ne.jp"],
    geoIds: ["190010"],
    url: "https://www.catv-jcta.jp/search/detail/10110158",
    coverage: "山梨県南アルプス市  市川三郷町  富士川町",
  },
  {
    name: "晴れの国ネット株式会社",
    domains: ["harenet.ne.jp"],
    geoIds: ["33"],
    url: "https://www.harenet.ad.jp/company",
    coverage: "岡山周辺",
  },
  {
    name: "株式会社光ネット",
    domains: ["hikari-net.ne.jp"],
    geoIds: ["360010"],
    url: "https://hikari-net.ne.jp/%e3%80%8c%e3%81%bf%e3%81%be%e3%81%ad%e3%81%a3%e3%81%a8%e3%80%8d%e3%82%a4%e3%83%b3%e3%82%bf%e3%83%bc%e3%83%8d%e3%83%83%e3%83%88%e3%82%b5%e3%83%bc%e3%83%93%e3%82%b9/",
    coverage: "美馬市",
  },
  {
    name: "(株)八戸テレビ放送",
    domains: ["htv-net.ne.jp"],
    geoIds: ["020030"],
    url: "https://www.catv-jcta.jp/search/detail/10110012",
    coverage: "青森県八戸市  南部町",
  },
  {
    name: "ジェットインターネット株式会社",
    domains: ["jet.ne.jp"],
    geoIds: ["040020", "040010"],
    url: "https://www.jet.ne.jp/jet-hikari/",
    coverage:
      "宮城県仙南(白石市、角田市、蔵王町、七ヶ宿町、大河原町、村田町、柴田町、川崎町、丸森町)",
  },
  {
    name: "ジェイコム鎌倉",
    domains: ["kamakuranet.ne.jp"],
    geoIds: ["140010"],
    url: "https://ja.wikipedia.org/wiki/%E3%82%B8%E3%82%A7%E3%82%A4%E3%82%B3%E3%83%A0%E9%8E%8C%E5%80%89",
    coverage: "神奈川県鎌倉市、逗子市",
  },
  {
    name: "峡東ケーブルネット(株)",
    domains: ["kcnet.ne.jp"],
    geoIds: ["190010"],
    url: "https://www.catv-jcta.jp/search/detail/10110153",
    coverage: "山梨県山梨市  甲州市",
  },
  {
    name: "けいはんなプラザ",
    domains: ["keihanna.ne.jp"],
    geoIds: ["260010"],
    url: "https://www.keihanna-plaza.co.jp/",
    coverage: "京都府",
  },
  {
    name: "エルシーブイ(株)",
    domains: ["lcv.ne.jp"],
    geoIds: ["200020", "200030"],
    url: "https://www.catv-jcta.jp/search/detail/10112058",
    coverage:
      "長野県岡谷市  諏訪市  茅野市  塩尻市  下諏訪町  富士見町  原村  辰野町",
  },
  {
    name: "(株)御前崎ケーブルテレビ",
    domains: ["maotv.ne.jp"],
    geoIds: ["220040"],
    url: "https://www.catv-jcta.jp/search/detail/10110222",
    coverage: "静岡県御前崎市",
  },
  {
    name: "鏡野町有線テレビ",
    domains: ["mto.ne.jp"],
    geoIds: ["330020"],
    url: "https://www.mto.ne.jp/",
    coverage: "岡山県鏡野町",
  },
  {
    name: "株式会社ネスク",
    domains: ["nsk.ne.jp"],
    geoIds: ["16", "17"],
    url: "https://www.nsk.ad.jp/",
    coverage: "富山、石川",
  },
  {
    name: "白根ケーブルネットワーク(株)",
    domains: ["nus.ne.jp"],
    geoIds: ["190010"],
    url: "https://www.catv-jcta.jp/search/detail/10112101",
    coverage: "山梨県南アルプス市",
  },
  {
    name: "株式会社シナプス",
    domains: ["synapse.ne.jp"],
    geoIds: ["46"],
    url: "https://corp.synapse.jp/",
    coverage: "鹿児島県",
  },
  {
    name: "TAM",
    domains: ["tam.ne.jp"],
    geoIds: 西日本,
    url: "https://tam.ne.jp/",
    description: "NTT西のみ",
    coverage: "西日本",
  },
  {
    name: "ジェイコム南横浜",
    domains: ["ttmy.ne.jp"],
    geoIds: ["140010"],
    url: "https://ja.wikipedia.org/wiki/%E3%82%B8%E3%82%A7%E3%82%A4%E3%82%B3%E3%83%A0%E5%8D%97%E6%A8%AA%E6%B5%9C",
    coverage: "神奈川県横浜市金沢区、港南区、栄区、戸塚区",
  },
  {
    name: "CBBS株式会社",
    domains: ["yamasemi.ne.jp"],
    geoIds: ["340020"],
    url: "https://www.cbbs.jp/",
    coverage: "広島県三次市",
  },
  {
    name: "(株)新川インフォメーションセンター",
    domains: ["nice-tv.jp"],
    geoIds: ["160010"],
    url: "https://www.catv-jcta.jp/search/detail/10110277",
    coverage: "富山県魚津市",
  },
  {
    name: "グローバルネットコア",
    domains: ["nplus-net.jp"],
    geoIds: ["15"],
    url: "https://www.global-netcore.jp/",
    description: "新潟近辺っぽい",
    coverage: "新潟近辺",
  },
  {
    name: "JANIS",
    domains: ["janis.or.jp"],
    geoIds: ["20"],
    url: "https://www.janis.jp/",
    coverage: "長野",
  },
  {
    name: "ミテネインターネット株式会社",
    domains: ["mitene.or.jp"],
    geoIds: ["18"],
    url: "https://www.mitene.co.jp/network/",
    description: "福井っぽい?",
    coverage: "福井",
  },
  {
    name: "フェニックスコミュニケーションズ株式会社",
    domains: ["rppp.jp"],
    geoIds: 東日本,
    url: "https://www.phoenix-c.or.jp/service/phoenix-hikari/",
    coverage: "東日本",
  },
  {
    name: "九州テレ・コミュニケーションズ(株)",
    domains: ["tvs12.jp"],
    geoIds: ["400010", "420020"],
    url: "https://www.catv-jcta.jp/search/detail/10110471",
    coverage:
      "福岡県筑紫野市  春日市  大野城市  太宰府市  那珂川市  宇美町  志免町  須恵町  粕屋町、長崎県佐世保市  佐々町",
  },
  {
    name: "雲南市・飯南町事務組合",
    domains: ["yoitoko.jp"],
    geoIds: ["320010"],
    url: "https://www.unnan-yume.net/",
    coverage: "島根県雲南市  飯南町",
  },
];

// ドメインからプロバイダー情報を検索するマップ
export const ProviderInfoByDomain: Record<string, ProviderInfo> =
  Object.fromEntries(
    ProviderInfoList.flatMap((info) =>
      info.domains.map((domain) => [domain, info]),
    ),
  );

// 後方互換性のため、既存のProviderMapも提供
export const ProviderMap: Record<string, GeoPosSuggestion[] | undefined> =
  Object.fromEntries(
    ProviderInfoList.flatMap((info) =>
      info.domains.map((domain) => [domain, info.geoIds]),
    ),
  ) as Record<string, GeoPosSuggestion[] | undefined>;
